Repository openiddict/openiddict-samples, pull requests merged in 2021-12, with the labels that each got.

#167 Remove the .NET Core SDK setup action and update .NET Arcade
  .github/workflows/build.yml
  eng/Version.Details.xml
  eng/common/SetupNugetSources.ps1
  eng/common/SetupNugetSources.sh
  eng/common/build.sh
  eng/common/cross/build-rootfs.sh
  eng/common/cross/toolchain.cmake
  eng/common/init-tools-native.sh
  eng/common/internal/Tools.csproj
  eng/common/native/common-library.sh
  eng/common/post-build/sourcelink-validation.ps1
  eng/common/sdk-task.ps1
  eng/common/sdl/configure-sdl-tool.ps1
  eng/common/sdl/execute-all-sdl-tools.ps1
  eng/common/sdl/extract-artifact-archives.ps1
  eng/common/sdl/run-sdl.ps1
  eng/common/templates/job/execute-sdl.yml
  eng/common/templates/job/job.yml
  eng/common/templates/job/publish-build-assets.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/steps/source-build.yml
  eng/common/tools.ps1
  eng/common/tools.sh
  global.json
Labels: enhancement, dependencies

#164 Update README.md
  README.md
Labels: enhancement

#168 Update Hollastin.Server to automatically create the SQL database using an IHostedService
  samples/Aridka/Aridka.Server/Startup.cs
  samples/Balosar/Balosar.Server/Startup.cs
  samples/Contruum/Contruum.Server/Startup.cs
  samples/Hollastin/Hollastin.Server/Startup.cs
  samples/Hollastin/Hollastin.Server/Worker.cs
  samples/Imynusoph/Imynusoph.Server/Startup.cs
  samples/Matty/Matty.Server/Startup.cs
  samples/Velusia/Velusia.Server/Startup.cs
  samples/Weytta/Weytta.Server/Startup.cs
  samples/Zirku/Zirku.Server/Startup.cs
Labels: bug

#170 Update the Aridka/Hollastin/Kalarba clients to use IdentityModel
  Packages.props
  samples/Aridka/Aridka.Client/Aridka.Client.csproj
  samples/Aridka/Aridka.Client/Program.cs
  samples/Hollastin/Hollastin.Client/Hollastin.Client.csproj
  samples/Hollastin/Hollastin.Client/Program.cs
  samples/Kalarba/Kalarba.Client/Kalarba.Client.csproj
  samples/Kalarba/Kalarba.Client/Program.cs
  samples/Kalarba/Kalarba.Server/Program.cs
  samples/Matty/Matty.Client/Matty.Client.csproj
  samples/Matty/Matty.Client/Program.cs
Labels: enhancement

#171 Remove direct references to JSON.NET and use the new System.Text.Json node APIs
  Packages.props
  samples/Contruum/Contruum.Server/Contruum.Server.csproj
  samples/Contruum/Contruum.Server/Pages/Connect/SignIn.cshtml.cs
  samples/Fornax/Fornax.Server/Fornax.Server.csproj
  samples/Fornax/Fornax.Server/Web.config
Labels: enhancement

#172 Use the new CreateAsyncScope() API introduced in .NET 6.0
  samples/Aridka/Aridka.Server/Worker.cs
  samples/Balosar/Balosar.Server/Worker.cs
  samples/Contruum/Contruum.Server/Worker.cs
  samples/Hollastin/Hollastin.Server/Worker.cs
  samples/Imynusoph/Imynusoph.Server/Worker.cs
  samples/Matty/Matty.Server/Worker.cs
  samples/Velusia/Velusia.Server/Worker.cs
  samples/Weytta/Weytta.Server/Worker.cs
  samples/Zirku/Zirku.Server/Worker.cs
Labels: enhancement

#175 Override the default email claim type used by ASP.NET Core Identity
  samples/Balosar/Balosar.Server/Startup.cs
  samples/Fornax/Fornax.Server/Web.config
  samples/Hollastin/Hollastin.Server/Startup.cs
  samples/Imynusoph/Imynusoph.Server/Startup.cs
  samples/Matty/Matty.Server/Startup.cs
  samples/Velusia/Velusia.Server/Startup.cs
  samples/Zirku/Zirku.Server/Startup.cs
Labels: enhancement

#176 Add a new minimal APIs sample
  OpenIddict.Samples.sln
  Packages.props
  README.md
  samples/Mimban/Mimban.Client/Mimban.Client.csproj
  samples/Mimban/Mimban.Client/Program.cs
  samples/Mimban/Mimban.Server/Mimban.Server.csproj
  samples/Mimban/Mimban.Server/Program.cs
  samples/Mimban/Mimban.Server/Properties/launchSettings.json
  samples/Mimban/Mimban.Server/appsettings.Development.json
  samples/Mimban/Mimban.Server/appsettings.json
Labels: enhancement
