Repository openiddict/openiddict-samples, pull requests merged in 2023-02, with the labels that each got.

#232 Switch to sqlite
  Directory.Packages.props
  samples/Aridka/Aridka.Server/Aridka.Server.csproj
  samples/Aridka/Aridka.Server/Startup.cs
  samples/Balosar/Balosar.Server/Balosar.Server.csproj
  samples/Balosar/Balosar.Server/Startup.cs
  samples/Contruum/Contruum.Server/Contruum.Server.csproj
  samples/Contruum/Contruum.Server/Startup.cs
  samples/Dantooine/Dantooine.Server/Dantooine.Server.csproj
  samples/Dantooine/Dantooine.Server/Startup.cs
  samples/Hollastin/Hollastin.Server/Hollastin.Server.csproj
  samples/Hollastin/Hollastin.Server/Startup.cs
  samples/Imynusoph/Imynusoph.Server/Imynusoph.Server.csproj
  samples/Imynusoph/Imynusoph.Server/Startup.cs
  samples/Matty/Matty.Server/Matty.Server.csproj
  samples/Matty/Matty.Server/Migrations/20210201201010_Init.Designer.cs
  samples/Matty/Matty.Server/Migrations/ApplicationDbContextModelSnapshot.cs
  samples/Matty/Matty.Server/Startup.cs
  samples/Mimban/Mimban.Server/Mimban.Server.csproj
  samples/Mimban/Mimban.Server/Program.cs
  samples/Velusia/Velusia.Client/Startup.cs
  samples/Velusia/Velusia.Client/Velusia.Client.csproj
  samples/Velusia/Velusia.Server/Migrations/20210201201010_Init.Designer.cs
  samples/Velusia/Velusia.Server/Migrations/ApplicationDbContextModelSnapshot.cs
  samples/Velusia/Velusia.Server/Startup.cs
  samples/Velusia/Velusia.Server/Velusia.Server.csproj
  samples/Weytta/Weytta.Server/Startup.cs
  samples/Weytta/Weytta.Server/Weytta.Server.csproj
  samples/Zirku/Zirku.Server/Program.cs
  samples/Zirku/Zirku.Server/Zirku.Server.csproj
Labels: enhancement

#234 Bump OpenIddict to 4.1 and update the client samples to use the new system integration package
  Directory.Packages.props
  samples/Fornax/Fornax.Client/Fornax.Client.csproj
  samples/Fornax/Fornax.Client/InteractiveService.cs
  samples/Fornax/Fornax.Client/Program.cs
  samples/Fornax/Fornax.Client/Worker.cs
  samples/Fornax/Fornax.Server/Web.config
  samples/Mimban/Mimban.Client/InteractiveService.cs
  samples/Mimban/Mimban.Client/Mimban.Client.csproj
  samples/Mimban/Mimban.Client/Program.cs
  samples/Mimban/Mimban.Client/Worker.cs
  samples/Mortis/Mortis.Client/Web.config
  samples/Mortis/Mortis.Server/Web.config
  samples/Weytta/Weytta.Client/InteractiveService.cs
  samples/Weytta/Weytta.Client/Program.cs
  samples/Weytta/Weytta.Client/Weytta.Client.csproj
  samples/Weytta/Weytta.Client/Worker.cs
  samples/Zirku/Zirku.Client/InteractiveService.cs
  samples/Zirku/Zirku.Client/Program.cs
  samples/Zirku/Zirku.Client/Worker.cs
  samples/Zirku/Zirku.Client/Zirku.Client.csproj
Labels: enhancement, dependencies

#235 Remove IdentityModel and IdentityModel.AspNetCore from Directory.Packages.props
  Directory.Packages.props
Labels: dependencies
