Repository openiddict/openiddict-samples, pull requests merged in 2024-08, with the labels that each got.

#332 Update the Dantooine sample to detect expired tokens and support token refreshing
  samples/Dantooine/Dantooine.Server/Startup.cs
  samples/Dantooine/Dantooine.Server/Worker.cs
  samples/Dantooine/Dantooine.WebAssembly.Server/Controllers/AuthenticationController.cs
  samples/Dantooine/Dantooine.WebAssembly.Server/Helpers/TokenRefreshingDelegatingHandler.cs
  samples/Dantooine/Dantooine.WebAssembly.Server/Helpers/TokenRefreshingForwarderHttpClientFactory.cs
  samples/Dantooine/Dantooine.WebAssembly.Server/Helpers/TokenRefreshingHttpResponseMessage.cs
  samples/Dantooine/Dantooine.WebAssembly.Server/Startup.cs
Labels: enhancement, sponsor

#334 Bump OpenIddict to 5.7.1
  Directory.Packages.props
Labels: dependencies

#335 Changed Zirku.Client2 ports to match the ones in the server.
  samples/Zirku/Zirku.Client2/Program.cs
  samples/Zirku/Zirku.Client2/Properties/launchSettings.json
Labels: bug, enhancement

#336 Bump OpenIddict to 5.8.0
  Directory.Packages.props
Labels: dependencies
