Repository openiddict/openiddict-samples, pull requests merged in 2025-04, with the labels that each got.

#357 Excludes Jetbrains IDE folders
  .gitignore
Labels: enhancement

#358 Use a static C# lang version in Directory.Build.props
  Directory.Build.props
Labels: enhancement, infrastructure

#359 Update the samples to use `TempData` to determine whether the user should be redirected to the login endpoint
  samples/Balosar/Balosar.Server/Controllers/AuthorizationController.cs
  samples/Contruum/Contruum.Server/Pages/Connect/Authorize.cshtml.cs
  samples/Dantooine/Dantooine.Server/Controllers/AuthorizationController.cs
  samples/Hollastin/Hollastin.Server/Controllers/AuthorizationController.cs
  samples/Imynusoph/Imynusoph.Server/Controllers/AuthorizationController.cs
  samples/Matty/Matty.Server/Controllers/AuthorizationController.cs
  samples/Velusia/Velusia.Server/Controllers/AuthorizationController.cs
  samples/Weytta/Weytta.Server/Controllers/AuthorizationController.cs
Labels: enhancement

#360 Bump OpenIddict to 6.2.1
  Directory.Packages.props
Labels: dependencies
